config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get '/not_authorized', to: 'home#not_authorized'

  devise_for :users
  as :user do
    get 'users/edit' => 'devise/registrations#edit',  :as => 'edit_user_registration'
    put 'users'      => 'registrations#update',       :as => 'user_registration'
  end
  resources  :users

  get 'sign_in_records/clear_filter'
  resources  :sign_in_records

  resources  :sign_in_record_imports

end

app/models/sign_in_record.rb
class SignInRecord < ApplicationRecord

  include Filterable
  include HasSortableName


  validates :first_name,   presence: true
  validates :last_name,    presence: true
  validates :room,         presence: true
  validates :label,        presence: true
  validates :sign_in_time, presence: true


  scope :with_first_name, ->(value) { where("lower(first_name) like lower(?)", "%#{value}%") }
  scope :with_last_name,  ->(value) { where("lower(last_name)  like lower(?)", "%#{value}%") }
  scope :in_room,         ->(value) { where room: value }
  scope :is_newcomer,     ->(value) { where newcomer: value }
  scope :for_today,       ->(value=true) { for_date(Date.today) }
  scope :on_or_after,     ->(value) { where("sign_in_time >= ?", value.beginning_of_day) }
  scope :on_or_before,    ->(value) { where("sign_in_time < ?",  value.end_of_day) }
  scope :for_date,        ->(value) { where("date(sign_in_time) = ?", value) }


  def self.room_list
    SignInRecord.distinct.order(:room).pluck(:room)
  end


  def self.unique_dates(limit)
      SignInRecord
        .distinct
        .order('date(sign_in_time) desc')
        .pluck('date(sign_in_time)')
        .take(limit)
        .map { |d| d.to_date }
  end


  def self.child_count(date)
    SignInRecord.for_date(date).count
  end


  def self.newcomer_count(date)
    SignInRecord.for_date(date).is_newcomer(true).count
  end


  def self.room_counts(date)
    SignInRecord.for_date(date).group(:room).count(:room)
  end


  def self.historic_counts
    SignInRecord
      .select('date(sign_in_time)')
      .order('date(sign_in_time)')
      .group('date(sign_in_time)')
      .count('date(sign_in_time)')
  end

end

app/controllers/sign_in_records_controller.rb
class SignInRecordsController < ApplicationController

  load_and_authorize_resource


  def index
    @title = 'Sign in records'
    @filter = get_filter
    @sign_in_records = SignInRecord.filter(@filter).order(sign_in_time: :desc)
    @sign_in_records = @sign_in_records.page(params[:page])
    set_filter @filter
    @rooms = SignInRecord.room_list
  end


  def clear_filter
    set_filter nil
    redirect_to action: :index
  end


  def show
    @title = 'Sign in record details'
  end



private

  def get_filter
    filter =
      params
        .permit(
          :order_by,
          :with_first_name,
          :with_last_name,
          :in_room,
          :is_newcomer,
          :for_today,
          :on_or_after,
          :on_or_before,
          :for_date,
        ).to_h
    filter = session[:filter_sign_in_records].symbolize_keys! if filter.empty? && session.key?(:filter_sign_in_records)
    filter = { :order_by => 'sign_in_time desc' } if filter.empty?
    filter.delete_if { |key, value| value.blank? }
    filter[:on_or_after]  = DateTime.parse(filter[:on_or_after])  if filter.key?(:on_or_after)
    filter[:on_or_before] = DateTime.parse(filter[:on_or_before]) if filter.key?(:on_or_before)
    filter[:for_date]     = DateTime.parse(filter[:for_date])     if filter.key?(:for_date)
    filter
  end


  def set_filter(filter)
    session[:filter_sign_in_records] = filter unless filter.nil?
    session.delete(:filter_sign_in_records) if filter.nil?
  end

end

app/views/sign_in_records/index.html.erb
<div class="actions-top">
  <div class="pull-right">
    <a class="btn btn-<%= @filter.except(:order_by).empty? ? "default" : "warning btn-outline" %>"
       data-toggle="collapse" data-target="#filter">
      <i class="fa fa-filter"></i> Filter
      <span class="caret"></span>
    </a>
  </div>
  <%= link_to new_sign_in_record_import_path, :class => 'btn btn-primary btn-sm' do %>
    <i class="fa fa-upload"></i> Import data
  <% end %>
</div>


<div class="row hidden-print">
  <div class="col-xs-12">
    <div id="filter" class="collapse">
      <div class="panel panel-default">
        <div class="panel-body">
        <%= form_tag sign_in_records_path, method: :get, class: "filter" do |f| %>
          <%= hidden_field_tag :order_by, @filter[:order_by] %>
          <div class="row">
            <div class="col-md-4">
              <div class="form-group">
                <%= label_tag :with_first_name, 'First name contains', :class => 'control-label' %>
                <%= text_field_tag :with_first_name, @filter[:with_first_name], :class => 'form-control' %>
              </div>
              <div class="form-group">
                <%= label_tag :with_last_name, 'Last name contains', :class => 'control-label' %>
                <%= text_field_tag :with_last_name, @filter[:with_last_name], :class => 'form-control' %>
              </div>
              <div class="form-group">
                <%= label_tag :is_newcomer, 'Just newcomers', :class => 'control-label' %>
                <div class="checkbox">
                  <%= label_tag :is_newcomer  do %>
                    <%= check_box_tag :is_newcomer, true, @filter[:is_newcomer] %> Yes
                  <% end %>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <%= label_tag :for_today, 'Today only', :class => 'control-label' %>
                <div class="checkbox">
                  <%= label_tag :for_today  do %>
                    <%= check_box_tag :for_today, true, @filter[:for_today] %> Yes
                  <% end %>
                </div>
              </div>
              <div class="form-group date days">
                <%= label_tag :for_date, 'For a specific date', :class => 'control-label' %>
                <div class="input-group date">
                  <span class="input-group-addon date"><i class="fa fa-calendar"></i></span>
                  <%= text_field_tag :for_date,
                                    (l(@filter[:for_date], :format => :date) if @filter.has_key?(:for_date)),
                                    :placeholder => 'dd/mm/yyyy',
                                    :class => 'form-control date' %>
                </div>
              </div>
              <div class="form-group date days">
                <%= label_tag :on_or_after, 'On or after', :class => 'control-label' %>
                <div class="input-group date">
                  <span class="input-group-addon date"><i class="fa fa-calendar"></i></span>
                  <%= text_field_tag :on_or_after,
                                    (l(@filter[:on_or_after], :format => :date) if @filter.has_key?(:on_or_after)),
                                    :placeholder => 'dd/mm/yyyy',
                                    :class => 'form-control date' %>
                </div>
              </div>
              <div class="form-group date days">
                <%= label_tag :on_or_before, 'On or before', :class => 'control-label' %>
                <div class="input-group date">
                  <span class="input-group-addon date"><i class="fa fa-calendar"></i></span>
                  <%= text_field_tag :on_or_before,
                                    (l(@filter[:on_or_before], :format => :date) if @filter.has_key?(:on_or_before)),
                                    :placeholder => 'dd/mm/yyyy',
                                    :class => 'form-control date' %>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <%= label_tag :in_room, 'Room', :class => 'control-label' %>
                <%= select_tag :in_room,
                      options_for_select(@rooms, @filter[:in_room]),
                      { prompt: "Please select a value...", class: 'form-control' } %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group pull-right">
                <%= link_to sign_in_records_clear_filter_path, :class => 'btn btn-default' do %>
                  <i class="fa fa-times"></i> Clear filter
                <% end %>
                <%= button_tag(type: "submit", class: "btn btn-primary") do %>
                  <i class="fa fa-filter"></i> Apply filter
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="table-responsive hidden-xs">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Room</th>
        <th>Date &amp; time</th>
        <th>Label</th>
        <th>Newcomer</th>
        <th> </th>
      </tr>
    </thead>
    <tbody>
      <% @sign_in_records.each do |record| %>
      <tr>
        <td><%= record.name %> </td>
        <td><%= record.room %> </td>
        <td><%= local_time(record.sign_in_time, :short) %> </td>
        <td><samp><%= record.label %></samp> </td>
        <td><%= yes_no_icon(record.newcomer) %> </td>
        <td align="right">
          <%= link_to sign_in_record_path(record), :class => '' do %>
            <i class="fa fa-info-circle"></i> View details
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<ul class="list-group list-group-striped hidden-sm hidden-md hidden-lg">
  <% @sign_in_records.each do |record| %>
  <li class="list-group-item">
    <div class="pull-right">
      <%= link_to sign_in_record_path(record), :class => 'btn btn-primary btn-outline btn-xs' do %>
        <i class="fa fa-info-circle"></i> View details
      <% end %>
    </div>
    <strong><%= record.name %></strong><br/>
    <%= record.room %><br/>
    <samp><%= record.label %></samp><br/>
    <small><%= local_time(record.sign_in_time, :short) %></small>
  </li>
  <% end %>
</ul>

<div class="pull-right">
  <%= paginate @sign_in_records %>
</div>

app/views/sign_in_records/show.html.erb
<div class="row">
  <div class="col-xs-12">

    <dl class="show">
      <dt>First name</dt>
      <dd><%= @sign_in_record.first_name %></dd>
      <dt>Last name</dt>
      <dd><%= @sign_in_record.last_name %></dd>
      <dt>Room</dt>
      <dd><%= @sign_in_record.room %></dd>
      <dt>Label</dt>
      <dd><samp><%= @sign_in_record.label %></samp></dd>
      <dt>Date &amp; time</dt>
      <dd><%= local_time(@sign_in_record.sign_in_time) %></dd>
      <dt>Newcomer</dt>
      <dd><%= yes_no_icon(@sign_in_record.newcomer) %></dd>
    </dl>

    <div class="actions-bottom">
      <%= link_to sign_in_records_path, :class => 'btn btn-outline btn-default btn-sm' do %>
        <i class="fa fa-reply"></i> Back to list
      <% end %>
    </div>
  </div>
</div>