config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get '/not_authorized', to: 'home#not_authorized'

  devise_for :users
  as :user do
    get 'users/edit' => 'devise/registrations#edit',  :as => 'edit_user_registration'
    put 'users'      => 'registrations#update',       :as => 'user_registration'
  end
  resources  :users

  get 'sign_in_records/clear_filter'
  resources  :sign_in_records

  resources  :sign_in_record_imports

end

app/models/sign_in_record_import.rb
class SignInRecordImport < ApplicationRecord

  has_attached_file :upload_file
  validates_attachment :upload_file, presence: true, content_type: { content_type: ["text/plain", "text/csv"] }

  has_attached_file :error_file
  validates_attachment_content_type :error_file, :content_type => ["text/plain", "text/csv"]


  enum status: [ :pending, :running, :complete ]


  def started_at
    created_at
  end


  def finished_at
    return updated_at if complete?
  end

end

app/controllers/sign_in_record_imports_controller.rb
class SignInRecordImportsController < ApplicationController

  load_and_authorize_resource


  def index
    @title = 'Import records'
    @sign_in_record_imports = SignInRecordImport.order(created_at: :desc)
    @sign_in_record_imports = @sign_in_record_imports.page(params[:page])
  end


  def show
    @title = 'Import details'
  end


  def new
    @title = 'Import data'
    @cancel_path = sign_in_record_imports_path
  end


  def create
    @sign_in_record_import = SignInRecordImport.new({ upload_file: params[:upload_file] })
    if @sign_in_record_import.save
      ImportSigninRecordsJob.perform_later @sign_in_record_import.id
      redirect_to( { action: 'index' }, notice: 'Import created successfully' )
    else
      @title       = 'Import data'
      @cancel_path = sign_in_record_imports_path
      render :new
    end
  end


end

app/views/sign_in_record_imports/index.html.erb
<div class="actions-top">
  <%= link_to new_sign_in_record_import_path, :class => 'btn btn-primary btn-sm' do %>
    <i class="fa fa-upload"></i> Import data
  <% end %>
</div>

<div class="table-responsive hidden-xs">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Started at</th>
        <th>Finished at</th>
        <th>Status</th>
        <th>Import count</th>
        <th>Error count</th>
        <th> </th>
      </tr>
    </thead>
    <tbody>
      <% @sign_in_record_imports.each do |record| %>
      <tr>
        <td><%= local_time(record.started_at, :long) %> </td>
        <td><%= record.finished_at.nil? ? '' : local_time(record.finished_at, :long) %> </td>
        <td><%= import_status(record) %> </td>
        <td><%= number_with_delimiter(record.success_count, delimiter: ',') unless record.success_count.nil? %> </td>
        <td><%= number_with_delimiter(record.error_count, delimiter: ',') unless record.error_count.nil? %> </td>
        <td align="right">
          <%= link_to sign_in_record_import_path(record), :class => '' do %>
            <i class="fa fa-info-circle"></i> View details
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<ul class="list-group list-group-striped hidden-sm hidden-md hidden-lg">
  <% @sign_in_record_imports.each do |record| %>
  <li class="list-group-item">
    <div class="pull-right">
      <%= link_to sign_in_record_import_path(record), :class => 'btn btn-primary btn-outline btn-xs' do %>
        <i class="fa fa-info-circle"></i> View details
      <% end %>
    </div>
    <strong><%= local_time(record.created_at, :short) %></strong><br/>
    <%= import_status(record) %>
  </li>
  <% end %>
</ul>

<div class="pull-right">
  <%= paginate @sign_in_record_imports %>
</div>

app/views/sign_in_record_imports/new.html.erb
<div class="row">
  <div class="col-xs-12 col-md-8 col-lg-6">

    <p class="text-muted">
      Upload a CSV file that contains valid sign in records.
    </p>

    <%= render partial: "errors", object: @sign_in_record_import, as: 'form' %>

    <%= bootstrap_form_tag url: sign_in_record_imports_path,
          method: :post, html: { multipart: true } do |f| %>

      <%= f.file_field  :upload_file, label: 'CSV File', accept: 'text/csv' %>

      <div class="form-group" style="margin-top: 20px;">
        <%= button_tag(type: "submit", class: "btn btn-primary") do %>
          <i class="fa fa-check"></i> Save
        <% end %>
        <%= link_to @cancel_path, :class => 'btn btn-default' do %>
          <i class="fa fa-times"></i> Cancel
        <% end %>
      </div>

    <% end %>

  </div>
</div>

app/views/sign_in_record_imports/show.html.erb
<div class="row">
  <div class="col-xs-12">

    <dl class="show">
      <dt>Started at</dt>
      <dd><%= local_time(@sign_in_record_import.started_at, :long) %></dd>
      <dt>Finished at</dt>
      <dd><%= @sign_in_record_import.finished_at.nil? ? '' : local_time(@sign_in_record_import.finished_at, :long) %> </dd>
      <dt>Status</dt>
      <dd><%= import_status(@sign_in_record_import) %></dd>
      <dt>Import count</dt>
      <dd><%= @sign_in_record_import.success_count.nil? ? 'N/A'
              : number_with_delimiter(@sign_in_record_import.success_count, delimiter: ',') %>
      </dd>
      <dt>Error count</dt>
      <dd><%= @sign_in_record_import.error_count.nil? ? 'N/A'
              : number_with_delimiter(@sign_in_record_import.error_count, delimiter: ',')%>
      </dd>
      <dt>Upload file</dt>
      <dd>
        <%= link_to @sign_in_record_import.upload_file.url do %>
        <i class="fa fa-file-excel-o"></i> View upload file
        <% end %>
      </dd>
      <% if @sign_in_record_import.error_file.exists? %>
      <dt>Upload file</dt>
      <dd>
        <%= link_to @sign_in_record_import.error_file.url do %>
        <i class="fa fa-file-excel-o"></i> View error file
        <% end %>
      </dd>
      <% end %>
    </dl>

    <div class="actions-bottom">
      <%= link_to sign_in_record_imports_path, :class => 'btn btn-outline btn-default btn-sm' do %>
        <i class="fa fa-reply"></i> Back to list
      <% end %>
    </div>
  </div>
</div>