config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get '/not_authorized', to: 'home#not_authorized'

  devise_for :users
  as :user do
    get 'users/edit' => 'devise/registrations#edit',  :as => 'edit_user_registration'
    put 'users'      => 'registrations#update',       :as => 'user_registration'
  end
  resources  :users

  get 'sign_in_records/clear_filter'
  resources  :sign_in_records

  resources  :sign_in_record_imports

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <title>Kids sign in | Causeway Coding</title>

  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

<body>

  <div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand text-uppercase" href="#">Kids sign in</a>
      </div>

      <% if user_signed_in? %>
      <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i> <%= current_user.name %> <i class="fa fa-caret-down"></i>
          </a>
          <ul class="dropdown-menu dropdown-user">
            <li><%= link_to edit_user_registration_path do %>
              <i class="fa fa-lock fa-fw"> </i> Change password<% end %>
            </li>
            <li class="divider"></li>
            <li><%= link_to(destroy_user_session_path, :method => :delete) do %>
              <i class="fa fa-sign-out fa-fw"> </i> Log out<% end %>
            </li>
          </ul>
        </li>
      </ul>
      <% end %>

      <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
          <ul class="nav" id="side-menu">
            <li>
              <%= link_to(root_path) do %>
                <i class="fa fa-dashboard fa-fw"> </i> Dashboard
              <% end %>
            </li>
            <li>
              <%= link_to(sign_in_records_path) do %>
                <i class="fa fa-check-square-o fa-fw"> </i> Sign in records
              <% end %>
            </li>
            <li>
              <%= link_to(sign_in_record_imports_path) do %>
                <i class="fa fa-upload fa-fw"> </i> Import records
              <% end %>
            </li>
            <% if can? :manage, User %>
            <li>
              <%= link_to(users_path) do %>
                <i class="fa fa-users fa-fw"> </i> Users
              <% end %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>

    </nav>

    <div id="page-wrapper">
      <% if @title %>
      <div class="row">
        <div class="col-lg-12">
          <h1 class="page-header"><%= @title %></h1>
        </div>
      </div>
      <% end %>
      <div class="row">
        <div class="col-lg-12">
          <%= yield %>
        </div>
      </div>
    </div>

  </div>

  <%= yield :scripts %>

</body>

<%= toastr_flash %>

</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Kids sign in | Causeway Coding</title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <%= yield %>
      </div>
    </div>
  </div>
</body>

</html>